### ISSUE TITLE
fog and volumetric light occlusion not working

### ISSUE THREAD

**Issue by Isaacthebomb360** [mseonKim/URP-VolumetricFog-ForwardPlus#2] opened 2024-07-29 21:12 UTC
I have no idea if i'm doing anything wrong but the fog in my scene isn't being occluded behind walls.

**Comment by Isaacthebomb360** [comment] 2024-07-29 21:20
![Screenshot 2024-07-29 231646](https://github.com/user-attachments/assets/a72c2b96-137d-45b1-b57b-c6122585c86a)

attached is an image of what I'm experiencing
the transparent block in the middle is an opaque material on a cube

**Comment by mseonKim** [comment] 2024-09-26 15:35
@Isaacthebomb306 Thanks for your feedback. It seems like the opaque material does not write depth to the camera depth buffer. Is it still reproducible if you use standard URP lit material for the block?

**Comment by Isaacthebomb360** [comment] 2024-10-01 11:47
Yes it is still reproducible

**Comment by mseonKim** [comment] 2024-10-12 15:06
@Isaacthebomb306 Can you give me the repro sample project?

**Comment by Isaacthebomb360** [comment] 2024-10-12 16:44
I just followed the instructions, 1 camera mostly shadows as a scene, and had a few spotlights. 
I was using Unity 2022.3.4f1

**Comment by mseonKim** [comment] 2024-10-13 15:22
I tried to reproduce it but it was hard to reproduce. Does it occur in Windows/DX11 or do you use other platforms such as Android?
![image](https://github.com/user-attachments/assets/5245de31-7580-4a61-a098-c4dc6581b65d)

**Comment by Isaacthebomb360** [comment] 2024-10-14 12:42
i used windows 10 i'm not sure if i was running DX 10 or 11

**Comment by mseonKim** [comment] 2024-10-14 14:10
Can you elaborate repro steps? Otherwise, I cannot resolve this issue without the repro sample project. :(

**Comment by Isaacthebomb360** [comment] 2024-11-03 16:01
i will reimport the package and try again, if the issue persists I will give you a step by step repro of what I did

**Comment by Isaacthebomb360** [comment] 2024-11-03 16:51
ok i found the issue, it was due to culling, I wasn't culling the lights from one of the two cameras so it was overwriting and causing visual and most likely performance issues

**Comment by mseonKim** [comment] 2024-11-19 13:11
Thanks for sharing. I'll close the issue because looks like it's not the volumetric fog package issue.

**Closed as completed** 2024-11-19 13:11 UTC
